window._appState = {"$meta": {"knbJS": "//s1.meituan.net/bs/knb/v1.6.5/knb.js",
                              "adunionJS": "//h5.dianping.com/app/adu-track/adunion-track.js",
                              "catJs": "//www.dpfile.com/app/owl/static/owl_1.8.1.js",
                              "catDevMode": false,
                              "uuid": "8286BFBE87039E2B154012F15396F5F32FEF6A1F3C028237FF9397B4AD30201C",
                              "iuuid": "8286BFBE87039E2B154012F15396F5F32FEF6A1F3C028237FF9397B4AD30201C",
                              "userId": "0",
                              "cityId": "304",
                              "userName": "",
                              "scene": "i",
                              "cityName": "泸州",
                              "id": 51331168,
                              "showAppDownload": false,
                              "appDownloadBannerConfig": {"isAndroid": true,
                                                          "isIPhone": false,
                                                          "isWx": false,
                                                          "isInApp": false,
                                                          "isOpenApp": true,
                                                          "isShow": true,
                                                          "isMt": false,
                                                          "isDp": false,
                                                          "dpdealId": "31593685",
                                                          "requestUrl": "https://i.meituan.com/deal/category/1/banner?userId=0&cityId=304&utm_source=",
                                                          "openAppUrl": "https://m.dianping.com/cube/evoke/meituan.html?url=imeituan%3A%2F%2Fwww.meituan.com%2Fdeal%3Fchannel%3Dfood%26did%3D51331168&web=https%3A%2F%2Fmeishi.meituan.com%2Fi%2Fdeal%2F51331168%3Fstid%3D019032296837928515275757042931456002187_c6_e639ffde6df45666f916d25e6e9b8c537%26cevent%3Dimt%252Fhomepage%252Fguess",
                                                          "appUrl": "imeituan://www.meituan.com/deal?channel=food&did=51331168",
                                                          "doNotOpenApp": false},
                              "appDownloadConfig": {"requestUrl": "https://i.meituan.com/deal/category/1/banner?userId=0&cityId=304&utm_source=",
                                                    "openAppUrl": "https://m.dianping.com/cube/evoke/meituan.html?url=imeituan%3A%2F%2Fwww.meituan.com%2Fdeal%3Fchannel%3Dfood%26did%3D51331168&web=https%3A%2F%2Fmeishi.meituan.com%2Fi%2Fdeal%2F51331168%3Fstid%3D019032296837928515275757042931456002187_c6_e639ffde6df45666f916d25e6e9b8c537%26cevent%3Dimt%252Fhomepage%252Fguess",
                                                    "appUrl": "imeituan://www.meituan.com/deal?channel=food&did=51331168",
                                                    "doNotOpenApp": false},
                              "pvLab": {"custom": {"source": "undefined"}},
                              "pageId": "c_yDrDR",
                              "title": "团购详情"},
                    "pageId": "c_yDrDR",
                    "title": "团购详情",
                    "detailInfo": {"id": 51331168,
                                   "slug": "51331168",
                                   "frontPoiCates": "1,59,20150",
                                   "channel": "food",
                                   "ctype": 0,
                                   "dtype": 0,
                                   "soldsDesc": "半年销量 1717",
                                   "start": 1527301622,
                                   "end": 1561391999,
                                   "status": 0,
                                   "state": 32,
                                   "showtype": "normal",
                                   "cityIds": [304],
                                   "price": 139,
                                   "value": 190,
                                   "campaigns": [],
                                   "campaignprice": 0,
                                   "canbuyprice": 0,
                                   "coupontitle": "仅售139元！最高价值190元的2—3人餐，可免费使用包间，提供免费WiFi。",
                                   "brandname": "守柴炉烤鸭",
                                   "range": "西南商贸城",
                                   "nobooking": 1,
                                   "terms": [{"title": "有效期",
                                              "content": ["2018.5.26 至 2019.6.24（周末、法定节假日通用）"]},
                                             {"title": "使用时间",
                                              "content": ["10:00-22:00"]},
                                             {"title": "使用规则",
                                              "content": ["团购用户不可同时享受商家其他优惠",
                                                          "酒水饮料等问题，请致电商家咨询，以商家反馈为准",
                                                          "如部分菜品因时令或其他不可抗因素导致无法提供，商家会用等价菜品替换，具体事宜请与商家协商",
                                                          "可免费使用包间",
                                                          "无需预约，消费高峰期可能需要等位",
                                                          "每桌最多使用1张美团券",
                                                          "每张美团券建议2至3人使用",
                                                          "商家提供免费WiFi",
                                                          "停车位收费标准：停车位问题请咨询商家",
                                                          "堂食外带均可，可以打包，打包费详情请咨询商家"]}],
                                   "menu": [[{"subtype": 1,
                                              "type": "0",
                                              "content": "菜品"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "守柴炉烤鸭",
                                              "specification": "1 份",
                                              "total": "88",
                                              "price": "88"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "酸萝卜鸭架汤",
                                              "specification": "1 份",
                                              "total": "25",
                                              "price": "25"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "烧椒土凉粉",
                                              "specification": "1 份",
                                              "total": "12",
                                              "price": "12"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "香卤鸭拼",
                                              "specification": "1 份",
                                              "total": "20",
                                              "price": "20"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "土豆",
                                              "specification": "1 份",
                                              "total": "6",
                                              "price": "6"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "白萝卜",
                                              "specification": "1 份",
                                              "total": "6",
                                              "price": "6"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "生菜",
                                              "specification": "1 份",
                                              "total": "6",
                                              "price": "6"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "葱油饼",
                                              "specification": "1 份",
                                              "total": "12",
                                              "price": "12"},
                                             {"subtype": 2,
                                              "type": "128",
                                              "content": "自助味碟",
                                              "specification": "3 份",
                                              "total": "15",
                                              "price": "5"},
                                             {"subtype": 1,
                                              "type": "0",
                                              "content": "备注"},
                                             {"subtype": 4,
                                              "type": "0",
                                              "content": "免费提供餐巾纸"}]],
                                   "howuse": {},
                                   "voice": "",
                                   "optionalattrs": {"11": "{\"endDate\":\"\",\"startDate\":\"\",\"useDay\":\"1\"}",
                                                     "81": "2—3人餐"},
                                   "buybutton": {"type": 4,
                                                 "text": "立即抢购",
                                                 "enabled": true},
                                   "rdploc": [{"cityId": 304,
                                               "poiid": 169321190,
                                               "name": "守柴炉烤鸭（龙马谭万达店）",
                                               "lat": 28.911444,
                                               "lng": 105.420243,
                                               "addr": "龙马潭区金带路万达广场4060-4061（西南商贸城旁）",
                                               "phone": "0830-2632116",
                                               "frontImg": "http://p0.meituan.net/deal/1d5260187e754996bc2967f378e208d855396.jpg@270w_270h_1e",
                                               "showStatus": 1,
                                               "avgScore": 4.9,
                                               "showType": "food",
                                               "isQueuing": 0,
                                               "areaid": 0,
                                               "areaName": "西南商贸城",
                                               "districtid": 3874,
                                               "districtname": "龙马潭区",
                                               "avgPrice": 57,
                                               "iUrl": ""}],
                                   "curcityrdcount": 1,
                                   "newrating": {"count": 320,
                                                 "rating": "4.0",
                                                 "recommend": 91,
                                                 "subcount": {"1": 6,
                                                              "2": 22,
                                                              "3": 55,
                                                              "4": 109,
                                                              "5": 128}},
                                   "imgurl": "//p0.meituan.net/deal/243d1f81e821efc26e5149f101ed986f136688.jpg",
                                   "squareimgurl": "http://p0.meituan.net/w.h/deal/243d1f81e821efc26e5149f101ed986f136688.jpg@84_0_534_534a%7C267h_267w_2e_90Q",
                                   "solds": 3348,
                                   "title": "2—3人餐，包间免费",
                                   "refund": 3,
                                   "fakerefund": 0,
                                   "sevenrefund": 1,
                                   "expireautorefund": 1,
                                   "todayavaliable": true,
                                   "isNewMarketDeal": false,
                                   "canPayOrder": true},
                    "stid": "019032296837928515275757042931456002187_c6_e639ffde6df45666f916d25e6e9b8c537",
                    "commentLabelsInfo": [{"count": 73,
                                           "isPositive": 1,
                                           "tag": "味道赞"},
                                          {"count": 66,
                                           "isPositive": 1,
                                           "tag": "分量足"},
                                          {"count": 52,
                                           "isPositive": 0,
                                           "tag": "烤鸭"},
                                          {"count": 43,
                                           "isPositive": 1,
                                           "tag": "菜品不错"},
                                          {"count": 39,
                                           "isPositive": 1,
                                           "tag": "性价比高"},
                                          {"count": 37,
                                           "isPositive": 1,
                                           "tag": "干净整洁"},
                                          {"count": 36,
                                           "isPositive": 1,
                                           "tag": "环境优雅"},
                                          {"count": 30,
                                           "isPositive": 1,
                                           "tag": "上菜快"},
                                          {"count": 28,
                                           "isPositive": 1,
                                           "tag": "价格实惠"},
                                          {"count": 24,
                                           "isPositive": 1,
                                           "tag": "回头客"}],
                    "albumPicsUrl": ["//p0.meituan.net/deal/243d1f81e821efc26e5149f101ed986f136688.jpg",
                                     "//p0.meituan.net/440.0/dealwatera/8d12da7a9d72087eea2e69ff0d052a73136688.jpg",
                                     "//p0.meituan.net/440.0/dealwatera/c2b052399c2dc2fe3413e65a64d05839129800.jpg",
                                     "//p0.meituan.net/440.0/dealwatera/f98177ed424e68ca88eacb8eb087d7f151451.jpg",
                                     "//p1.meituan.net/440.0/dealwatera/adf8fe786fe5bee50e19457ea2f16046118308.jpg"],
                    "adsParam": {"viewDealId": 51331168,
                                 "viewShopId": "",
                                 "categoryIds": "1,59,20150"},
                    "relatedDealParam": {"did": 51331168}}
